name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-24.04
    env:
      MIX_ENV: test
    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              elixir: "1.15"
              otp: "24.3.4.10"
          - pair:
              elixir: "1.18.4"
              otp: "27.3.4"
            lint: lint
    steps:
      - uses: actions/checkout@v3

      - uses: erlef/setup-beam@main
        with:
          otp-version: ${{ matrix.pair.otp }}
          elixir-version: ${{ matrix.pair.elixir }}
          version-type: strict

      - uses: actions/cache@v3
        with:
          path: deps
          key: mix-deps-${{ hashFiles('**/mix.lock') }}

      - run: mix deps.get

      - run: mix format --check-formatted
        if: ${{ matrix.lint }}

      - run: mix deps.unlock --check-unused
        if: ${{ matrix.lint }}

      - run: mix deps.compile

      - run: mix compile --no-optional-deps --warnings-as-errors
        if: ${{ matrix.lint }}

      - run: mix test --slowest 5
        if: ${{ ! matrix.lint }}

      - run: mix test --slowest 5 --warnings-as-errors
        if: ${{ matrix.lint }}
